server:
  port: 8080
  servlet:
    context-path: /studentcourse

spring:
    datasource:
        name: test
        url: jdbc:mysql://45.76.169.58:3306/studentcourse_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: student_test
        password: test
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
      cache: false
      encoding: utf-8
      #决定使用什么模板 不然无法找到对应的页面 html5 要求严格
      #mode: HTML5
      mode: LEGACYHTML5
      servlet:
        content-type: text/html


## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: www.studentcourse.tk.model  # 注意：对应实体类的路径

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql